/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.trly.sandbox

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
