server:
  port: 8089

management:
  health:
    db:
      enabled: true
  endpoint:
    health.show-details: ALWAYS
management.health.diskspace.enabled: true
management.health.livenessstate.enabled: true
