name: Sourcegraph Code Intelligence

on:
  push:
    branches: [main]

jobs:
  scip-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        # adjust as needed for your project
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Coursier
        uses: coursier/setup-action@v1

      - name: Generate SCIP index
        run: cs launch com.sourcegraph:scip-java_2.13:0.11.2 -- index

      - name: Upload index artifact
        uses: actions/upload-artifact@v6
        with:
          name: scip-index
          path: index.scip
          retention-days: 1

  code-intel-upload:
    runs-on: ubuntu-latest
    needs: scip-index
    container:
      image: sourcegraph/src-cli:latest
    steps:
      - name: Download index artifact
        uses: actions/download-artifact@v7
        with:
          name: scip-index

      - name: Upload to Sourcegraph
        run: src code-intel upload -github-token ${{ secrets.GITHUB_TOKEN  }}
        env:
          SRC_ENDPOINT: ${{ secrets.SRC_ENDPOINT }}
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN }}
